# Generated by Django 6.0.2 on 2026-02-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
