print("Name:Mamatamayee Sahoo")
print("Father:Ranjit Kumar Sahoo")
print("Village:Julanga")
print("Post Office:Kantiokateni")
print("District:Dhenkanal")
print("PIN:759026")
print("Mobile:8926036280")
print("Age:22")
print("Marriage:False")