print("enter your Name")
N=input()
print("enter your age")
A=int(input())
print("enter your marriage status")
Mr=bool(input())
print("enter your height")
Ht=float(input())
print("Name:",N)
print("Age:",A)
print("Marriage:",Mr)
print("Height:",Ht)